-- Execute uma vez no Supabase > SQL Editor.
create table if not exists public.ferias_periodos (
  id bigint generated by default as identity primary key,
  vendedor_ausente text not null,
  data_inicio date not null,
  data_fim date not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.ferias_clientes (
  periodo_id bigint not null references public.ferias_periodos(id) on delete cascade,
  cnpj text not null,
  cliente text not null,
  cidade text,
  filial text,
  responsavel_atual text,
  media_base numeric not null default 0,
  primary key (periodo_id, cnpj)
);

create table if not exists public.ferias_snapshots (
  periodo_id bigint not null references public.ferias_periodos(id) on delete cascade,
  data_analise date not null,
  cnpj text not null,
  responsavel_atual text,
  venda_mes numeric not null default 0,
  retencao numeric not null default 0,
  devolucao numeric not null default 0,
  dias_sem_venda integer,
  primary key (periodo_id, data_analise, cnpj)
);

create table if not exists public.ferias_feedbacks (
  id bigint generated by default as identity primary key,
  periodo_id bigint not null references public.ferias_periodos(id) on delete cascade,
  cnpj text not null,
  cliente text not null,
  responsavel text not null,
  status text not null default 'Pendente',
  descricao text not null,
  data_feedback date not null default current_date,
  criado_em timestamptz not null default now()
);

alter table public.ferias_periodos enable row level security;
alter table public.ferias_clientes enable row level security;
alter table public.ferias_snapshots enable row level security;
alter table public.ferias_feedbacks enable row level security;

create policy "ferias_periodos_publico" on public.ferias_periodos for all to anon using (true) with check (true);
create policy "ferias_clientes_publico" on public.ferias_clientes for all to anon using (true) with check (true);
create policy "ferias_snapshots_publico" on public.ferias_snapshots for all to anon using (true) with check (true);
create policy "ferias_feedbacks_publico" on public.ferias_feedbacks for all to anon using (true) with check (true);
